const bioData = {
    name : 'Rizka Zahraini Nurmis',
    age : 20,
    hobbies : ['Reading', 'singing', 'watching'],
    isMarried : false,
    schoolList : [
        {name : 'TK Aisyiyah Rempoa, Jakarta Selatan', 
        yearIn : 2001, 
        yearOut : 2002, 
        major : null}, 
        {name : 'SDN 009 Pagi Kecamatann Pesanggrahan, Jakarta Selatan', 
        yearIn : 2002, 
        yearOut : 2005, 
        major : null},
        {name : 'SDN 006 Pagi Kecamatan Bambu Apus, Jakarta Timur', 
        yearIn : 2005, 
        yearOut : 2007, 
        major : null},
        {name : 'SDN 009 Sekupang, Batam, Kepulauan Riau', 
        yearIn : 2007, 
        yearOut : 2007, 
        major : null},
        {name : 'SDN 01 Koto Tangah Batuhampa, Kecamatan Akabiluru, Kab. 50 Kota, Sumatera Barat', 
        yearIn : 2007, 
        yearOut : 2008, 
        major : null},
        {name : 'SMP Negeri 4 Payakumbuh', 
        yearIn : 2008, 
        yearOut : 2011, 
        major : null},
        {name : 'SMA Negeri 2 Payakumbuh', 
        yearIn : 2011, 
        yearOut : 2014, 
        major : 'IPA'},
        {name : 'Universitas Andalas, Padang', 
        yearIn : 2015, 
        yearOut : 2019, 
        major : 'Matematika'}
    ],
    skills : [
        {skillName : 'Microsoft Office', level : 'Advanced'},
        {skillName : 'SPSS', level : 'Advanced'},
        {skillName : 'Minitab', level : 'Advanced'},
        {skillName : 'LaTex', level : 'Advanced'},
        {skillName : 'R Programming', level : 'Beginner'},
        {skillName : 'MatLab', level : 'Beginner'}
    ],
    interestInCoding : true
}
console.log(bioData);